# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fe7026f63c8cfe28cdd93d9ca0e6a15b"
name = "synergistic-account-app"
handle = "synergistic-account-app-9"
application_url = "https://6724-2401-4900-77af-9a73-b456-ce62-c954-95d1.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "alpha-store-ds.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://6724-2401-4900-77af-9a73-b456-ce62-c954-95d1.ngrok-free.app"
]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
