# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fe7026f63c8cfe28cdd93d9ca0e6a15b"
name = "synergistic-account-app"
handle = "synergistic-account-app-9"
application_url = "https://d07f-203-110-242-44.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "alpha-store-ds.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://d07f-203-110-242-44.ngrok-free.app/auth/callback" ]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
